#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2024-present ROCKNIX (https://github.com/ROCKNIX)

. /etc/profile

# Get Internal LED State
LED_STATE=$(get_setting "led.color")
if [ ! -n "${LED_STATE}" ]; then
  LED_STATE="flow"
  set_setting "led.color" "flow"
fi

if [ ! -d "/sys/class/gpio/gpio65" ]; then
  echo 65 > /sys/class/gpio/export
  echo out >/sys/class/gpio/gpio65/direction
  echo 1 >/sys/class/gpio/gpio65/value
fi

# Run LED control at boot
/usr/bin/ledcontrol ${LED_STATE}
