#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 JELOS (https://github.com/JustEnoughLinuxOS)

cat <<EOF >/storage/.config/profile.d/001-device_config
# Device Features
DEVICE_PLAYBACK_PATH_SPK="HP"
DEVICE_PLAYBACK_PATH_HP="SPK"
DEVICE_PWR_LED_GPIO="77"

DEVICE_FUNC_KEYA_MODIFIER="BTN_TRIGGER_HAPPY1"
DEVICE_FUNC_KEYB_MODIFIER="BTN_TRIGGER_HAPPY2"

DEVICE_TEMP_SENSOR="/sys/devices/virtual/thermal/thermal_zone0/temp"
EOF
