#!/bin/bash
# make by G.R.H

RATMPCONF="/storage/.config/retroarch/retroarch.cfg"
RAAPPENDCONF="/tmp/.retroarch.cfg"

Last_Game=`grep '"path":' /storage/.config/retroarch/content_history.lpl | head -1`
Last_Core=`grep '"core_path":' /storage/.config/retroarch/content_history.lpl | head -1`
PLATFORM="${Last_Game#*/}"
PLATFORM="${PLATFORM#*/}"
PLATFORM="${PLATFORM#*/}"
PLATFORM="${PLATFORM%%/*}"
Last_Game="${Last_Game%\"*}"
Last_Game="${Last_Game##*\"}"
Last_Core="${Last_Core%\"*}"
Last_Core="${Last_Core##*\"}"
Last_Core="$(basename "$Last_Core")"
Last_Core="${Last_Core%_*}"

if [ -e "/sys/firmware/devicetree/base/model" ]; then
  MY_DEVICE="$(tr -d '\0' </sys/firmware/devicetree/base/model 2>/dev/null)"
else
  MY_DEVICE="$(tr -d '\0' </sys/class/dmi/id/sys_vendor 2>/dev/null) $(tr -d '\0' </sys/class/dmi/id/product_name 2>/dev/null)"
fi
MY_DEVICE="$(echo ${MY_DEVICE} | sed -e "s#[/]#-#g")"
case ${MY_DEVICE} in
    "Anbernic RG353P"|"Anbernic RG353M"|"Anbernic RG353V"|"Anbernic RG503"|"Powkiddy RK2023"|"Powkiddy RGB30")
        CONTROLLERSCONFIG=" -p1index 0 -p1guid 19009b4d4b4800000111000000010000"
    ;;
    "Anbernic RG351M"|"Anbernic RG351V")
        CONTROLLERSCONFIG=" -p1index 0 -p1guid 03002758091200000031000011010000"
    ;;
    "Anbernic RG552")
        CONTROLLERSCONFIG=" -p1index 0 -p1guid 19009b4d4b4800000111000000020000"
    ;;
    "Anbernic Win600")
        CONTROLLERSCONFIG=""
    ;;
    "ODROID-GO Super")
        CONTROLLERSCONFIG=" -p1index 0 -p1guid 1900c3ea010000000100000001010000"
    ;;
    "Powkiddy RGB10")
        CONTROLLERSCONFIG=" -p1index 0 -p1guid 1900dea8010000000200000001010000"
    ;;
    "Powkiddy RGB10 MAX 3")
        CONTROLLERSCONFIG=" -p1index 0 -p1guid 03001354474f2d556c74726120476100"
    ;;
    "Powkiddy x55")
        CONTROLLERSCONFIG=" -p1index 0 -p1guid 1900fcf27a65645f6a6f797374696300"
    ;;
esac

/usr/bin/runemu.sh "$Last_Game" -P"$PLATFORM" --core="$Last_Core" --emulator=retroarch --controllers="$CONTROLLERSCONFIG"

rm -f $0
